/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cikbohay;

import javax.swing.WindowConstants;

/**
 *
 * @author rizal
 */
public class Kasirtransaksi extends javax.swing.JPanel {

    // Variabel untuk mengingat transaksi terakhir yang mau dicetak
    public static String idNotaTerakhir = "";

    /**
     * Creates new form Kasirtransaksi
     */
    public Kasirtransaksi() {
        initComponents();
        reset();

        // Ubah warna tombol struk jadi abu-abu saat kasir pertama kali dibuka
        btnStruk2.setBackground(java.awt.Color.GRAY);

        // Mengosongkan baris default bawaan NetBeans pada tabel pesanan
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPesanan2.getModel();
        model.setRowCount(0);
    }

    void reset() {
        tKode2.setText(null);
        tNamaMenu2.setText(null);
        tHarga2.setText(null);
        tJumlah2.setText(null);
//        tUangBayar2.setText(null);
//        tKembalian2.setText(null);
//        tSubTotal2.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        input = new javax.swing.JPanel();
        kasir = new javax.swing.JPanel();
        inputTransaksi2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        tKode2 = new javax.swing.JTextField();
        tNamaMenu2 = new javax.swing.JTextField();
        tHarga2 = new javax.swing.JTextField();
        tJumlah2 = new javax.swing.JTextField();
        btnTambah2 = new javax.swing.JButton();
        btnHapus2 = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPesanan2 = new javax.swing.JTable();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        tUangBayar2 = new javax.swing.JTextField();
        tKembalian2 = new javax.swing.JTextField();
        tSubTotal2 = new javax.swing.JTextField();
        btnQris2 = new javax.swing.JButton();
        btnCash2 = new javax.swing.JButton();
        btnStruk2 = new javax.swing.JButton();
        menuKasir = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(505, 533));
        setRequestFocusEnabled(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        kasir.setMaximumSize(new java.awt.Dimension(1099, 32767));
        kasir.setLayout(new java.awt.GridLayout(1, 0));

        inputTransaksi2.setMaximumSize(new java.awt.Dimension(0, 0));
        inputTransaksi2.setPreferredSize(new java.awt.Dimension(0, 0));
        inputTransaksi2.setRequestFocusEnabled(false);
        inputTransaksi2.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setPreferredSize(new java.awt.Dimension(505, 50));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel46.setText("Kasir");

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-profile-20.png"))); // NOI18N

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-bell-20.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addGap(64, 64, 64)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addGap(7, 7, 7)
                .addComponent(jLabel49)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        inputTransaksi2.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel15.setBackground(new java.awt.Color(181, 72, 72));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel51.setText("Input Transaksi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel16.add(jLabel51, gridBagConstraints);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setText("Kode/Barcode");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel16.add(jLabel52, gridBagConstraints);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel53.setText("Nama Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanel16.add(jLabel53, gridBagConstraints);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("Harga (Rp)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 18, 0, 0);
        jPanel16.add(jLabel54, gridBagConstraints);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setText("Jumlah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        jPanel16.add(jLabel55, gridBagConstraints);

        tKode2.setEditable(false);
        tKode2.setBackground(new java.awt.Color(204, 204, 204));
        tKode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKode2MouseClicked(evt);
            }
        });
        tKode2.addActionListener(this::tKode2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel16.add(tKode2, gridBagConstraints);

        tNamaMenu2.setBackground(new java.awt.Color(204, 204, 204));
        tNamaMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNamaMenu2MouseClicked(evt);
            }
        });
        tNamaMenu2.addActionListener(this::tNamaMenu2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        jPanel16.add(tNamaMenu2, gridBagConstraints);

        tHarga2.setEditable(false);
        tHarga2.setBackground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        jPanel16.add(tHarga2, gridBagConstraints);

        tJumlah2.setBackground(new java.awt.Color(204, 204, 204));
        tJumlah2.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 124;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        jPanel16.add(tJumlah2, gridBagConstraints);

        btnTambah2.setBackground(new java.awt.Color(51, 204, 0));
        btnTambah2.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-plus-20.png"))); // NOI18N
        btnTambah2.setText("Tambah");
        btnTambah2.addActionListener(this::btnTambah2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 28, 10, 0);
        jPanel16.add(btnTambah2, gridBagConstraints);

        btnHapus2.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus2.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-trash-20.png"))); // NOI18N
        btnHapus2.setText("Hapus");
        btnHapus2.addActionListener(this::btnHapus2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 58, 10, 0);
        jPanel16.add(btnHapus2, gridBagConstraints);

        btnReset2.setBackground(new java.awt.Color(255, 204, 0));
        btnReset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-reset-20.png"))); // NOI18N
        btnReset2.setText("Reset");
        btnReset2.addActionListener(this::btnReset2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 103, 10, 58);
        jPanel16.add(btnReset2, gridBagConstraints);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel56.setText("Daftar Pesanan");
        jLabel56.setPreferredSize(new java.awt.Dimension(100, 20));
        jLabel56.setRequestFocusEnabled(false);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel57.setText("Total belanja");
        jLabel57.setPreferredSize(new java.awt.Dimension(100, 20));

        tblPesanan2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jScrollPane4.setViewportView(tblPesanan2);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Uang Bayar");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setText("Kembalian");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel60.setText("Subtotal");

        tUangBayar2.setBackground(new java.awt.Color(204, 204, 204));
        tUangBayar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tUangBayar2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tUangBayar2KeyTyped(evt);
            }
        });

        tKembalian2.setEditable(false);
        tKembalian2.setBackground(new java.awt.Color(204, 204, 204));

        tSubTotal2.setEditable(false);
        tSubTotal2.setBackground(new java.awt.Color(204, 204, 204));

        btnQris2.setBackground(new java.awt.Color(0, 153, 255));
        btnQris2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-qr-code-20.png"))); // NOI18N
        btnQris2.setText("Qris");
        btnQris2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQris2MouseClicked(evt);
            }
        });
        btnQris2.addActionListener(this::btnQris2ActionPerformed);

        btnCash2.setBackground(new java.awt.Color(51, 204, 0));
        btnCash2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-cash-20.png"))); // NOI18N
        btnCash2.setText("Cash");
        btnCash2.addActionListener(this::btnCash2ActionPerformed);

        btnStruk2.setBackground(new java.awt.Color(255, 204, 0));
        btnStruk2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-note-20.png"))); // NOI18N
        btnStruk2.setText("Struk");
        btnStruk2.addActionListener(this::btnStruk2ActionPerformed);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane4)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tUangBayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addGap(18, 18, 18)
                                .addComponent(tKembalian2)))
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tSubTotal2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQris2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCash2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStruk2)))))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel60)
                    .addComponent(tUangBayar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel59)
                    .addComponent(tKembalian2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQris2)
                    .addComponent(btnCash2)
                    .addComponent(btnStruk2))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        inputTransaksi2.add(jPanel15, java.awt.BorderLayout.CENTER);

        kasir.add(inputTransaksi2);

        javax.swing.GroupLayout inputLayout = new javax.swing.GroupLayout(input);
        input.setLayout(inputLayout);
        inputLayout.setHorizontalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kasir, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
        );
        inputLayout.setVerticalGroup(
            inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
            .addGroup(inputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inputLayout.createSequentialGroup()
                    .addComponent(kasir, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(input);

        menuKasir.setLayout(new java.awt.CardLayout());
        add(menuKasir);
    }// </editor-fold>//GEN-END:initComponents

//    // Method ini wajib public static agar bisa dipanggil dari Qris.java
//    public static void tampilkanMenu() {
//        cikbohay.dashboardAdmin adminView = new cikbohay.dashboardAdmin();
//        cikbohay.dashboardAdmin.isKasirMode = true;
//
//        // Sembunyikan tombol admin
//        adminView.btnTambahMenu.setVisible(false);
//        adminView.btnEditMenu.setVisible(false);
//        adminView.btnHapusMenu.setVisible(false);
//
//        // --- KUNCI JAWABANNYA ADA DI SINI ---
//        // Kita harus "memaksa" adminView untuk menghitung ukuran komponennya
//        // meskipun jendelanya tidak kita tampilkan (invisible).
//        adminView.pack();
//
//        // Copot isi panel kanan, lalu pasang menu
//        menuKasir.removeAll();
//        menuKasir.setLayout(new java.awt.BorderLayout());
//        menuKasir.add(adminView.tampilanMenu, java.awt.BorderLayout.CENTER);
//
//        // Refresh UI
//        menuKasir.revalidate();
//        menuKasir.repaint();
//    }

    private void btnStruk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStruk2ActionPerformed
        // TODO add your handling code here:
// 1. Cek apakah ada ID Nota yang tersimpan?
        if (idNotaTerakhir.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Tidak ada transaksi untuk dicetak!\nSilakan pilih metode pembayaran (Cash/QRIS) terlebih dahulu.",
                    "Peringatan Cetak Struk",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Panggil panel Struk_cikbohay
        Struk_cikbohay panelStruk = new Struk_cikbohay();

        // --- TAMBAHKAN BARIS INI UNTUK MENYUNTIKKAN DATA KE STRUK ---
        panelStruk.muatDataStruk(idNotaTerakhir);

        // --- KODINGAN BARU: Bungkus JPanel ke dalam JDialog ---
        javax.swing.JDialog jendelaStruk = new javax.swing.JDialog();
        jendelaStruk.setTitle("Cetak Struk - Cik Bohay");
        jendelaStruk.setModal(true); // Modal = Jendela ini harus ditutup dulu baru bisa klik form kasir lagi
        jendelaStruk.getContentPane().add(panelStruk); // Masukkan panel struk ke dalam jendela
        jendelaStruk.pack(); // Sesuaikan ukuran jendela otomatis dengan ukuran panel

        // Sekarang setLocationRelativeTo BISA BERJALAN karena dipasang di JDialog!
        jendelaStruk.setLocationRelativeTo(this);
        jendelaStruk.setVisible(true); // Tampilkan pop-up struknya
        // ------------------------------------------------------

        // 3. MATIKAN LAGI tombol struknya setelah sukses dipanggil (Kembali ke mode awal)
        idNotaTerakhir = "";
        btnStruk2.setBackground(java.awt.Color.GRAY);
    }//GEN-LAST:event_btnStruk2ActionPerformed

    private void btnCash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash2ActionPerformed
        // TODO add your handling code here:
        // ==========================================
        // 1. VALIDASI AWAL KASIR
        // ==========================================
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPesanan2.getModel();

        // Cek apakah keranjang kosong
        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Keranjang masih kosong, tidak ada yang bisa disimpan!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Bersihkan karakter selain angka dari Subtotal dan Uang Bayar
        String subtotalRaw = tSubTotal2.getText().replaceAll("[^\\d]", "");
        String bayarRaw = tUangBayar2.getText().replaceAll("[^\\d]", "");

        if (bayarRaw.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan nominal Uang Bayar terlebih dahulu!");
            return;
        }

        long subtotal = Long.parseLong(subtotalRaw);
        long bayar = Long.parseLong(bayarRaw);

        // Cek apakah uangnya cukup
        if (bayar < subtotal) {
            javax.swing.JOptionPane.showMessageDialog(this, "Uang pembayaran kurang dari total belanja!", "Peringatan", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ==========================================
        // 2. PROSES PENYIMPANAN DATABASE
        // ==========================================
        try {
            java.sql.Connection conn = koneksi.konek(); // Panggil koneksi database
            java.sql.Statement st = conn.createStatement();

            // --- A. GENERATE ID NOTA OTOMATIS (Format: NTA000001 -> char 9) ---
            String idNota = "NTA000001";
            java.sql.ResultSet rsNota = st.executeQuery("SELECT MAX(id_nota) FROM nota");
            if (rsNota.next() && rsNota.getString(1) != null) {
                long urut = Long.parseLong(rsNota.getString(1).substring(3)) + 1;
                idNota = "NTA" + String.format("%06d", urut);
            }

            // --- B. INSERT DATA KE TABEL NOTA ---
            String sqlNota = "INSERT INTO nota (id_nota, waktu_transaksi, total_pesanan, metode_pembayaran) VALUES (?, ?, ?, ?)";
            java.sql.PreparedStatement psNota = conn.prepareStatement(sqlNota);
            psNota.setString(1, idNota);
            psNota.setTimestamp(2, new java.sql.Timestamp(System.currentTimeMillis())); // Rekam waktu saat ini (Real-time)
            psNota.setBigDecimal(3, new java.math.BigDecimal(subtotal));
            psNota.setString(4, "Cash"); // Masukkan metode sesuai ENUM
            psNota.executeUpdate();

            // --- C. PREPARE ID PESANAN OTOMATIS (Format: PSN0000001 -> char 10) ---
            long urutPesanan = 1;
            java.sql.ResultSet rsPesanan = st.executeQuery("SELECT MAX(id_pesanan) FROM pesanan");
            if (rsPesanan.next() && rsPesanan.getString(1) != null) {
                urutPesanan = Long.parseLong(rsPesanan.getString(1).substring(3)) + 1;
            }

            // --- D. LOOPING: INSERT SEMUA BARANG KE TABEL PESANAN ---
            String sqlPesanan = "INSERT INTO pesanan (id_pesanan, jumlah, total, id_menu, id_kasir, id_nota) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement psPesanan = conn.prepareStatement(sqlPesanan);

            for (int i = 0; i < model.getRowCount(); i++) {
                // Cetak ID Pesanan baru untuk setiap baris barang
                String idPesanan = "PSN" + String.format("%07d", urutPesanan++);

                // Ambil ID Menu (Ingat trik sebelumnya: kita memotong teks "mnu0001 - Seblak Jeletot")
                String menuTampil = model.getValueAt(i, 0).toString();
                String idMenu = menuTampil.split(" - ")[0];

                // Ambil jumlah dan subtotal per baris
                int jumlah = Integer.parseInt(model.getValueAt(i, 2).toString());
                String totalBarisRaw = model.getValueAt(i, 3).toString().replaceAll("[^\\d]", "");
                java.math.BigDecimal totalBaris = new java.math.BigDecimal(totalBarisRaw);

                // Eksekusi Insert
                psPesanan.setString(1, idPesanan);
                psPesanan.setInt(2, jumlah);
                psPesanan.setBigDecimal(3, totalBaris);
                psPesanan.setString(4, idMenu);
                psPesanan.setString(5, "ksr01"); // Saya hardcode ke akun kasir yang ada di databasemu
                psPesanan.setString(6, idNota);
                psPesanan.executeUpdate();
            }

            // ==========================================
            // 3. FINALISASI (BERSIHKAN LAYAR)
            // ==========================================
            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi Cash Berhasil!\nKembalian: " + tKembalian2.getText(), "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // ========================================================
            // LANGKAH 4: NYALAKAN TOMBOL STRUK UNTUK CASH
            // ========================================================
            idNotaTerakhir = idNota; // Simpan ID Nota ke ingatan statis
            btnStruk2.setBackground(new java.awt.Color(255, 204, 0)); // Ubah warna jadi kuning kembali

            javax.swing.JOptionPane.showMessageDialog(this, "Transaksi Cash Berhasil!\nSilakan cetak struk.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Baru setelah itu keranjang dibersihkan
            model.setRowCount(0);
            tUangBayar2.setText("");
            tKembalian2.setText("");
            reset();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi: " + e.getMessage(), "Error Database", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCash2ActionPerformed

    private void btnQris2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQris2ActionPerformed
        // TODO add your handling code here:
        // 1. Validasi keranjang kosong
        if (tSubTotal2.getText().isEmpty() || tSubTotal2.getText().equals("Rp 0")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Keranjang masih kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Otomatis set uang bayar pas sesuai subtotal
        tUangBayar2.setText(tSubTotal2.getText());
        hitungKembalian();

        // 3. Panggil panel Qris
        Qris panelQris = new Qris();

        // 4. BUNGKUS PANEL QRIS JADI POP-UP JENDELA (Persis kayak Struk!)
        javax.swing.JDialog jendelaQris = new javax.swing.JDialog();
        jendelaQris.setTitle("Pembayaran QRIS - Cik Bohay");
        jendelaQris.setModal(true); // Mengunci layar kasir agar fokus ke QRIS
        jendelaQris.getContentPane().add(panelQris);
        jendelaQris.pack();

        // Munculkan di tengah layar
        jendelaQris.setLocationRelativeTo(this);
        jendelaQris.setVisible(true);
    }//GEN-LAST:event_btnQris2ActionPerformed

    private void btnQris2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQris2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQris2MouseClicked

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus2ActionPerformed
        // TODO add your handling code here:
        // 1. Cek apakah kasir sudah memilih baris di tabel keranjang (tblPesanan2)
        int barisTerpilih = tblPesanan2.getSelectedRow();

        if (barisTerpilih == -1) {
            // Kalau belum klik tabel, kasih peringatan
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Silakan pilih pesanan di keranjang yang ingin dihapus terlebih dahulu!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Hentikan proses
        }

        // 2. Ambil nama menu dari baris yang diklik untuk ditampilkan di pesan konfirmasi
        // Di tabelmu, nama menu ada di kolom pertama (index 0)
        String menuYangDihapus = tblPesanan2.getValueAt(barisTerpilih, 0).toString();

        // 3. Tampilkan Pop-up Konfirmasi Hapus
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin membatalkan/menghapus pesanan:\n" + menuYangDihapus + "?",
                "Konfirmasi Hapus Pesanan",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        // 4. Jika kasir mengklik "YES"
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            // Panggil model tabelnya
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPesanan2.getModel();

            // Hapus baris yang sedang dipilih
            model.removeRow(barisTerpilih);

            // HITUNG ULANG TOTAL BELANJA! (Supaya subtotal otomatis berkurang)
            hitungTotalBelanja();

            // Bersihkan form inputan kasir
            reset();
        }
    }//GEN-LAST:event_btnHapus2ActionPerformed

    private void hitungTotalBelanja() {
        int totalBelanja = 0;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPesanan2.getModel();

// Cek bagian looping di hitungTotalBelanja:
        for (int i = 0; i < model.getRowCount(); i++) {
            // Ambil index 3 (Kolom Subtotal)
            String subtotalRaw = model.getValueAt(i, 3).toString().replaceAll("[^\\d]", "");
            totalBelanja += Long.parseLong(subtotalRaw);
        }

        // Tampilkan totalnya ke textfield SubTotal di layar
        String formatTitik = String.format("%,d", totalBelanja).replace(',', '.');
        tSubTotal2.setText("Rp " + formatTitik);
    }

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
        // 1. VALIDASI: Pastikan kasir sudah milih menu dan isi jumlah
        if (tKode2.getText().isEmpty() || tJumlah2.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih menu dan masukkan jumlah terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. AMBIL DATA
            String idMenu = tKode2.getText();
            String namaMenu = tNamaMenu2.getText();

            // Bersihkan "Rp" dan titik dari harga biar jadi angka murni
            String hargaRaw = tHarga2.getText().replaceAll("[^\\d]", "");
            int harga = Integer.parseInt(hargaRaw);

            // Ambil jumlah pesanan
            int jumlah = Integer.parseInt(tJumlah2.getText());

            // 3. HITUNG SUBTOTAL PER ITEM
            int subtotal = harga * jumlah;

            // 4. FORMAT TAMPILAN KE TABEL
            String hargaFormat = "Rp " + String.format("%,d", harga).replace(',', '.');
            String subtotalFormat = "Rp " + String.format("%,d", subtotal).replace(',', '.');

            // Trik Jitu: Gabungkan ID dan Nama Menu di kolom pertama.
            // Nanti waktu mau nyimpen ke database, kita tinggal potong teksnya buat ambil ID-nya aja.
            String menuTampil = idMenu + " - " + namaMenu;

            // 5. MASUKKAN KE KERANJANG (tblPesanan2)
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPesanan2.getModel();
            model.addRow(new Object[]{
                menuTampil, // Kolom Menu
                hargaFormat, // Kolom Harga
                jumlah, // Kolom Jumlah
                subtotalFormat // Kolom Subtotal
            });

            // 6. HITUNG ULANG TOTAL SELURUH BELANJA
            hitungTotalBelanja();

            // 7. BERSIHKAN FORM (Siap untuk menu berikutnya)
            // Tambahkan ini di baris akhir btnTambah2ActionPerformed
            hitungTotalBelanja();
            hitungKembalian();
            reset();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah dengan format angka yang benar!");
        }
        tKode2.requestFocus(); // Kursor otomatis balik ke barcode
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void tNamaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaMenu2ActionPerformed

    private void tNamaMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNamaMenu2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tNamaMenu2MouseClicked

    private void tKode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKode2ActionPerformed

    private void tKode2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKode2MouseClicked
        // 1. Buat object dari dashboardAdmin
        cikbohay.dashboardAdmin adminView = new cikbohay.dashboardAdmin();

        // 2. Bersihkan panel utama tempat menu muncul
        menuKasir.removeAll(); // Ganti "menuKasir" dengan nama panel/container di kode kamu

        // 3. Langsung masukkan tampilanMenu dari object adminView
        menuKasir.add(adminView.tampilanMenu);

        // 4. Refresh tampilan
        menuKasir.repaint();
        menuKasir.revalidate();
    }//GEN-LAST:event_tKode2MouseClicked

    private void tUangBayar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tUangBayar2KeyTyped
        // TODO add your handling code here:
        char huruf = evt.getKeyChar();

        // Jika yang diketik bukan angka, maka tolak inputannya
        if (!Character.isDigit(huruf)) {
            evt.consume();
        }
    }//GEN-LAST:event_tUangBayar2KeyTyped

    private void hitungKembalian() {
        try {
            // Ambil angka murni dari Subtotal
            String subtotalRaw = tSubTotal2.getText().replaceAll("[^\\d]", "");
            long subtotal = subtotalRaw.isEmpty() ? 0 : Long.parseLong(subtotalRaw);

            // Ambil angka murni dari Uang Bayar
            String bayarRaw = tUangBayar2.getText().replaceAll("[^\\d]", "");
            long bayar = bayarRaw.isEmpty() ? 0 : Long.parseLong(bayarRaw);

            // Hitung selisihnya
            long kembalian = bayar - subtotal;

            // Jika uangnya kurang, tampilkan Rp 0 atau biarkan kosong
            if (kembalian < 0) {
                tKembalian2.setText("Rp 0");
            } else {
                // Jika uang pas atau lebih, format menjadi Rupiah
                String formatKembalian = String.format("%,d", kembalian).replace(',', '.');
                tKembalian2.setText("Rp " + formatKembalian);
            }
        } catch (NumberFormatException e) {
            System.out.println("Error hitung kembalian: " + e.getMessage());
        }
    }

    private void tUangBayar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tUangBayar2KeyReleased
        // TODO add your handling code here:
        String uangRaw = tUangBayar2.getText().replaceAll("[^\\d]", "");

        if (!uangRaw.isEmpty()) {
            try {
                long angka = Long.parseLong(uangRaw);
                String formatTitik = String.format("%,d", angka).replace(',', '.');
                tUangBayar2.setText("Rp " + formatTitik);

                // PANGGIL METHOD KEMBALIAN DI SINI!
                hitungKembalian();

            } catch (NumberFormatException e) {
                System.out.println("Error format uang: " + e.getMessage());
            }
        } else {
            tUangBayar2.setText("");
            tKembalian2.setText("");
        }
    }//GEN-LAST:event_tUangBayar2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCash2;
    private javax.swing.JButton btnHapus2;
    private javax.swing.JButton btnQris2;
    private javax.swing.JButton btnReset2;
    public static javax.swing.JButton btnStruk2;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JPanel input;
    private javax.swing.JPanel inputTransaksi2;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel kasir;
    public static javax.swing.JPanel menuKasir;
    public static javax.swing.JTextField tHarga2;
    public static javax.swing.JTextField tJumlah2;
    public static javax.swing.JTextField tKembalian2;
    public static javax.swing.JTextField tKode2;
    public static javax.swing.JTextField tNamaMenu2;
    public static javax.swing.JTextField tSubTotal2;
    public static javax.swing.JTextField tUangBayar2;
    public static javax.swing.JTable tblPesanan2;
    // End of variables declaration//GEN-END:variables
}
