/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cikbohay;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author macbookairm12020
 */
public class TambahMenuAdmin extends javax.swing.JPanel {
    public boolean modeEdit = false;

    /**
     * Creates new form TambahMenuAdmin
     */
    public TambahMenuAdmin() {
        initComponents();
        comboKategori();
        reset();
        setKodeOtomatis();
    }

    private void setKodeOtomatis() {
        try {
            // Ganti 'kode_menu' dan 'tabel_menu' sesuai dengan nama kolom dan tabel di database-mu
            String sql = "SELECT id_menu FROM menu ORDER BY id_menu DESC LIMIT 1";
            java.sql.Connection con = (java.sql.Connection) koneksi.konek(); // Sesuaikan dengan class koneksimu
            java.sql.Statement st = con.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                // Kalau data sudah ada, ambil kode terakhir
                String kodeTerakhir = rs.getString("id_menu");

                // Potong 3 huruf pertama ("mnu"), ambil sisa angkanya, lalu tambah 1
                String angkaSaja = kodeTerakhir.substring(3);
                int angkaBaru = Integer.parseInt(angkaSaja) + 1;

                // Format ulang jadi "mnu" + 4 digit angka (misal: 1 jadi 0001)
                String kodeBaru = String.format("mnu%04d", angkaBaru);

                // Masukkan ke Text Field kodemu (sesuaikan nama variabelnya)
                tIdMenu.setText(kodeBaru);
            } else {
                // Kalau tabel masih kosong melompong, set kode pertama
                tIdMenu.setText("mnu0001");
            }

            // Bikin field-nya nggak bisa diedit manual biar aman
            tIdMenu.setEditable(false);

        } catch (Exception e) {
            System.out.println("Error bikin kode otomatis: " + e.getMessage());
        }
    }

    //mengubah pilihan nama pada cKategori menjadi id_kategori
    String IdKategori(String NamaKategori) {
        try {
            String sql = "SELECT * FROM kategori WHERE nama_kategori = ?";

            Connection con = koneksi.konek();

            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, NamaKategori);

            ResultSet resultSet = ps.executeQuery();

            while (resultSet.next()) {
                return resultSet.getString("id_kategori");
            }
        } catch (SQLException sQLException) {
            return "";

        }
        return "";
    }

    //mengisi cKategori dengan nama kategori dari database
    void comboKategori() {
        try {
            String sql = "SELECT * FROM kategori";

            Connection con = koneksi.konek();

            Statement statement = con.createStatement();

            ResultSet resultSet = statement.executeQuery(sql);

            while (resultSet.next()) {
                cKategori.addItem(resultSet.getString("nama_kategori"));
            }
        } catch (SQLException sQLException) {

        }
        cKategori.setSelectedItem(null);
    }

    void reset() {
        tNamaMenu.setText(null);
        tHarga.setText(null);
        cKategori.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tIdMenu = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        tNamaMenu = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        tPesanMenu = new javax.swing.JLabel();
        cKategori = new javax.swing.JComboBox<>();
        btnTambahMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(181, 72, 72));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel2.setText("ID MENU               :");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel3.setText("KATEGORI            :");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel4.setText("HARGA                  :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel5.setText("NAMA MENU         :");

        tIdMenu.setBackground(new java.awt.Color(204, 204, 204));
        tIdMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        tHarga.setBackground(new java.awt.Color(204, 204, 204));
        tHarga.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tHargaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tHargaKeyTyped(evt);
            }
        });

        tNamaMenu.setBackground(new java.awt.Color(204, 204, 204));
        tNamaMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnReset.setBackground(new java.awt.Color(255, 204, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-reset-20.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        tPesanMenu.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        tPesanMenu.setText("TAMBAH MENU BARU");

        cKategori.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnTambahMenu.setBackground(new java.awt.Color(0, 204, 51));
        btnTambahMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTambahMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-plus-20.png"))); // NOI18N
        btnTambahMenu.setText("Tambahkan Menu");
        btnTambahMenu.addActionListener(this::btnTambahMenuActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNamaMenu))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tHarga)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 40, Short.MAX_VALUE)
                                .addComponent(btnTambahMenu))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIdMenu)
                            .addComponent(cKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tPesanMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tPesanMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tIdMenu)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tNamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/logo_cikbohay31.jpeg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CIK BOHAY");
        jLabel8.setToolTipText("");

        jLabel9.setBackground(new java.awt.Color(255, 153, 51));
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Managemen System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        // TODO add your handling code here:

        String IdMenu = tIdMenu.getText();

        String Kategori = IdKategori(cKategori.getSelectedItem().toString());

        String NamaMenu = tNamaMenu.getText();

// GANTI dengan baris di bawah ini biar yang masuk ke DB cuma ANGKA-nya saja (15000)
        String Harga = tHarga.getText().replaceAll("[^\\d]", "");

        Object itemKategori = cKategori.getSelectedItem();
        String NamaKategori = (itemKategori != null) ? itemKategori.toString() : "";

        // 2. PASANG SATPAM (VALIDASI KOSONG) DI SINI
        if (IdMenu.isEmpty() || NamaMenu.isEmpty() || Harga.isEmpty() || NamaKategori.isEmpty()) {
            // Munculkan pop-up peringatan
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Harap isi semua kolom terlebih dahulu!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);

            // RETURN sangat penting! Ini yang bikin Java berhenti dan batal masuk ke try-catch SQL
            return;
        }
        
        try {
            Connection con = koneksi.konek();
            PreparedStatement statement;

            if (modeEdit == true) {
                // MODE EDIT: Jalankan UPDATE
                String sql = "UPDATE menu SET id_kategori=?, nama_menu=?, harga=? WHERE id_menu=?";
                statement = con.prepareStatement(sql);
                statement.setString(1, Kategori);
                statement.setString(2, NamaMenu);
                statement.setString(3, Harga);
                statement.setString(4, IdMenu); // ID taruh di akhir karena WHERE
                statement.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
            } else {
                // MODE TAMBAH BARU: Jalankan INSERT
                String sql = "INSERT INTO menu (id_menu, id_kategori, nama_menu, harga) VALUES (?, ?, ?, ?)";
                statement = con.prepareStatement(sql);
                statement.setString(1, IdMenu);
                statement.setString(2, Kategori);
                statement.setString(3, NamaMenu);
                statement.setString(4, Harga);
                statement.execute();
                javax.swing.JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            }

//            // Tutup pop-up
//            javax.swing.wi window = javax.swing.SwingUtilities.getWindowAncestor(this);
//            if (window instanceof javax.swing.JDialog) {
//                window.dispose();
//            }
        } catch (SQLException sQLException) {
            javax.swing.JOptionPane.showMessageDialog(null, "Data gagal diproses! " + sQLException.getMessage());
        }
        setKodeOtomatis();
        reset();
    }//GEN-LAST:event_btnTambahMenuActionPerformed

    private void tHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHargaKeyTyped
        // TODO add your handling code here:
        char huruf = evt.getKeyChar();
        // Jika yang diketik bukan angka, abaikan/tolak
        if (!Character.isDigit(huruf)) {
            evt.consume();
        }
    }//GEN-LAST:event_tHargaKeyTyped

    private void tHargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tHargaKeyReleased
        // TODO add your handling code here:
        // 1. Ambil teks yang ada sekarang, lalu hapus semua karakter selain angka
    String hargaRaw = tHarga.getText().replaceAll("[^\\d]", "");
    
    // 2. Kalau field-nya nggak kosong, kita format angkanya
    if (!hargaRaw.isEmpty()) {
        try {
            long angka = Long.parseLong(hargaRaw);
            
            // Format angka menjadi ribuan dengan titik (contoh: 15.000)
            String formatTitik = String.format("%,d", angka).replace(',', '.');
            
            // Set kembali ke text field ditambah tulisan "Rp " di depannya
            tHarga.setText("Rp " + formatTitik);
            
        } catch (NumberFormatException e) {
            System.out.println("Error format harga: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_tHargaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    public javax.swing.JButton btnTambahMenu;
    public javax.swing.JComboBox<String> cKategori;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField tHarga;
    public javax.swing.JTextField tIdMenu;
    public javax.swing.JTextField tNamaMenu;
    public javax.swing.JLabel tPesanMenu;
    // End of variables declaration//GEN-END:variables
}
