/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cikbohay;

import java.awt.CardLayout; //agar bisa pindah kartu menampilkan menu per keategori
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class tampilanMenu extends javax.swing.JFrame {

    /**
     * Creates new form tampilanMenu
     */
    public tampilanMenu() {
        initComponents();
        load_tabel_menu_semua();
        load_tabel_menu_seblak();
        load_tabel_menu_geprek();
        load_tabel_menu_minuman();
        load_tabel_menu_mie();
    }

    private void pindahKartuMenu(String namaKartuMenu) {
        CardLayout cl
                =//variabel cl (dengan tipe data atau apalah) CardLayout 
                (CardLayout) panelMenu.getLayout(); //mengambil kartu dari panel utama

        cl.show //menunjukkan kartu
                (panelMenu, namaKartuMenu); //dari kartu utama, diambil kartu yang mana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTambahMenu = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnHapusMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tombolMenu = new javax.swing.JPanel();
        btnMenuSemua = new javax.swing.JButton();
        btnMenuSeblak = new javax.swing.JButton();
        btnMenuGeprek = new javax.swing.JButton();
        btnMenuMinuman = new javax.swing.JButton();
        btnMenuSnack = new javax.swing.JButton();
        btnMenuMie = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        cardMenuSemua = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenuSemua = new javax.swing.JTable();
        cardMenuSeblak = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenuSeblak = new javax.swing.JTable();
        cardMenuGeprek = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMenuGeprek = new javax.swing.JTable();
        cardMenuMinuman = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMenuMinuman = new javax.swing.JTable();
        cardMenuSnack = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMenuSnack = new javax.swing.JTable();
        cardMenuMie = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMenuMie = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setText("Menu Cik Bohay");
        jPanel1.add(jLabel1);

        btnTambahMenu.setBackground(new java.awt.Color(0, 204, 51));
        btnTambahMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambahMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icons8-plus-20.png"))); // NOI18N
        btnTambahMenu.setText("Tambah Menu Baru");
        btnTambahMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahMenu);

        btnEditMenu.setBackground(new java.awt.Color(255, 204, 0));
        btnEditMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEditMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icone/icons8-white-edit-20.png"))); // NOI18N
        btnEditMenu.setText("Edit Menu");
        jPanel1.add(btnEditMenu);

        btnHapusMenu.setBackground(new java.awt.Color(255, 51, 51));
        btnHapusMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapusMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cikbohay/icone/icons8-remove-20.png"))); // NOI18N
        btnHapusMenu.setText("Hapus Menu");
        jPanel1.add(btnHapusMenu);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tombolMenu.setLayout(new java.awt.GridLayout(1, 0));

        btnMenuSemua.setText("Semua");
        btnMenuSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSemuaActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuSemua);

        btnMenuSeblak.setText("Seblak");
        btnMenuSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSeblakActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuSeblak);

        btnMenuGeprek.setText("Geprek");
        btnMenuGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuGeprekActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuGeprek);

        btnMenuMinuman.setText("Minuman");
        btnMenuMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMinumanActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuMinuman);

        btnMenuSnack.setText("Snack");
        btnMenuSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSnackActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuSnack);

        btnMenuMie.setText("Mie LVL");
        btnMenuMie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMieActionPerformed(evt);
            }
        });
        tombolMenu.add(btnMenuMie);

        jPanel2.add(tombolMenu, java.awt.BorderLayout.PAGE_START);

        panelMenu.setLayout(new java.awt.CardLayout());

        cardMenuSemua.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuSemua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMenuSemua);

        cardMenuSemua.add(jScrollPane1);

        panelMenu.add(cardMenuSemua, "card2");

        cardMenuSeblak.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuSeblak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblMenuSeblak);

        cardMenuSeblak.add(jScrollPane2);

        panelMenu.add(cardMenuSeblak, "card2");

        cardMenuGeprek.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuGeprek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMenuGeprek);

        cardMenuGeprek.add(jScrollPane3);

        panelMenu.add(cardMenuGeprek, "card2");

        cardMenuMinuman.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuMinuman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblMenuMinuman);

        cardMenuMinuman.add(jScrollPane4);

        panelMenu.add(cardMenuMinuman, "card2");

        cardMenuSnack.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuSnack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblMenuSnack);

        cardMenuSnack.add(jScrollPane5);

        panelMenu.add(cardMenuSnack, "card2");

        cardMenuMie.setLayout(new java.awt.GridLayout(1, 0));

        tblMenuMie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblMenuMie);

        cardMenuMie.add(jScrollPane6);

        panelMenu.add(cardMenuMie, "card2");

        jPanel2.add(panelMenu, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMieActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuMie");//menamppilkan menu Mie LVL
    }//GEN-LAST:event_btnMenuMieActionPerformed

            void load_tabel_menu_mie() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");
        
        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu WHERE id_kategori = 'k001'";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");
                
                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuMie.setModel(model);
    }
            
    private void btnMenuSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSemuaActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuSemua");//menamppilkan semua menu
    }//GEN-LAST:event_btnMenuSemuaActionPerformed

    public void load_tabel_menu_semua() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");

        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");

                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuSemua.setModel(model);
    }

    private void btnMenuSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSeblakActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuSeblak");//menamppilkan menu seblak
    }//GEN-LAST:event_btnMenuSeblakActionPerformed

    void load_tabel_menu_seblak() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");

        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu WHERE id_kategori = 'k001'";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");

                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuSeblak.setModel(model);
    }

    private void btnMenuGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuGeprekActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuGeprek");//menamppilkan menu Geprek
    }//GEN-LAST:event_btnMenuGeprekActionPerformed

    void load_tabel_menu_geprek() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");

        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu WHERE id_kategori = 'k002'";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");

                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuGeprek.setModel(model);
    }

    private void btnMenuMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMinumanActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuMinuman");//menamppilkan menu Minuman
    }//GEN-LAST:event_btnMenuMinumanActionPerformed

    void load_tabel_menu_minuman() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");

        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu WHERE id_kategori = 'k003'";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");

                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuMinuman.setModel(model);
    }

    private void btnMenuSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSnackActionPerformed
        // TODO add your handling code here:
        pindahKartuMenu("cardMenuSnack");//menamppilkan menu Snack
    }//GEN-LAST:event_btnMenuSnackActionPerformed

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTambahMenuActionPerformed

        void load_tabel_menu_snack() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID MENU");

        model.addColumn("Nama Menu");

        model.addColumn("Harga");

        model.addColumn("Kategori");

        String sql = "SELECT * FROM menu WHERE id_kategori = 'k003'";

        try {
            Connection con = koneksi.konek();

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                String idMenu = rs.getString("id_menu");

                String namaMenu = rs.getString("nama_menu");

                String harga = rs.getString("harga");

                String idKategori = rs.getString("id_kategori");

                Object[] baris = {idMenu, namaMenu, harga, idKategori};
                model.addRow(baris);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        tblMenuSnack.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilanMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditMenu;
    public javax.swing.JButton btnHapusMenu;
    private javax.swing.JButton btnMenuGeprek;
    private javax.swing.JButton btnMenuMie;
    private javax.swing.JButton btnMenuMinuman;
    private javax.swing.JButton btnMenuSeblak;
    private javax.swing.JButton btnMenuSemua;
    private javax.swing.JButton btnMenuSnack;
    public javax.swing.JButton btnTambahMenu;
    private javax.swing.JPanel cardMenuGeprek;
    private javax.swing.JPanel cardMenuMie;
    private javax.swing.JPanel cardMenuMinuman;
    private javax.swing.JPanel cardMenuSeblak;
    private javax.swing.JPanel cardMenuSemua;
    private javax.swing.JPanel cardMenuSnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblMenuGeprek;
    private javax.swing.JTable tblMenuMie;
    private javax.swing.JTable tblMenuMinuman;
    private javax.swing.JTable tblMenuSeblak;
    private javax.swing.JTable tblMenuSemua;
    private javax.swing.JTable tblMenuSnack;
    private javax.swing.JPanel tombolMenu;
    // End of variables declaration//GEN-END:variables
}
